// GENERATED by scripts/encode.ts from clips/manifest.json. Do not edit.
// Regenerate with: npm run encode
import type { ClipEntry } from "@/lib/clips.types";

export const clips = {
  "placeholder-dusk": {
      "id": "placeholder-dusk",
      "hash": "1e4a9c42",
      "ratio": "16:9",
      "focal": {
          "x": 0.5,
          "y": 0.45
      },
      "loop": "xfade",
      "duration": 7.5,
      "approved": false,
      "hero": true,
      "files": {
          "mp4_720": "/clips/placeholder-dusk.1e4a9c42.720.mp4",
          "poster": "/clips/placeholder-dusk.1e4a9c42.jpg",
          "mp4_1080": "/clips/placeholder-dusk.1e4a9c42.1080.mp4",
          "poster_1920": "/clips/placeholder-dusk.1e4a9c42.poster.1920.jpg"
      }
  },
  "placeholder-harbor": {
      "id": "placeholder-harbor",
      "hash": "32bf96dc",
      "ratio": "16:9",
      "focal": {
          "x": 0.5,
          "y": 0.5
      },
      "loop": "xfade",
      "duration": 7.5,
      "approved": false,
      "hero": false,
      "files": {
          "mp4_720": "/clips/placeholder-harbor.32bf96dc.720.mp4",
          "poster": "/clips/placeholder-harbor.32bf96dc.jpg",
          "mp4_1080": "/clips/placeholder-harbor.32bf96dc.1080.mp4",
          "poster_1920": "/clips/placeholder-harbor.32bf96dc.poster.1920.jpg"
      }
  },
  "placeholder-rise": {
      "id": "placeholder-rise",
      "hash": "7876e9c5",
      "ratio": "16:9",
      "focal": {
          "x": 0.5,
          "y": 0.5
      },
      "loop": "pingpong",
      "duration": 7.9,
      "approved": false,
      "hero": false,
      "files": {
          "mp4_720": "/clips/placeholder-rise.7876e9c5.720.mp4",
          "poster": "/clips/placeholder-rise.7876e9c5.jpg",
          "mp4_1080": "/clips/placeholder-rise.7876e9c5.1080.mp4",
          "poster_1920": "/clips/placeholder-rise.7876e9c5.poster.1920.jpg"
      }
  },
  "placeholder-sound": {
      "id": "placeholder-sound",
      "hash": "530936d4",
      "ratio": "16:9",
      "focal": {
          "x": 0.6,
          "y": 0.5
      },
      "loop": "none",
      "duration": 8,
      "approved": false,
      "hero": false,
      "files": {
          "mp4_720": "/clips/placeholder-sound.530936d4.720.mp4",
          "poster": "/clips/placeholder-sound.530936d4.jpg",
          "mp4_1080": "/clips/placeholder-sound.530936d4.1080.mp4",
          "poster_1920": "/clips/placeholder-sound.530936d4.poster.1920.jpg"
      }
  },
} as const satisfies Record<string, ClipEntry>;

export type ClipId = keyof typeof clips;
export const clipIds = Object.keys(clips) as ClipId[];
