// GENERATED by scripts/encode.ts from clips/manifest.json. Do not edit.
// Regenerate with: npm run encode
import type { ClipEntry } from "@/lib/clips.types";

export const clips = {
  "sailboat-sunset": {
      "id": "sailboat-sunset",
      "hash": "e825e0b7",
      "entryHash": "d21b17b8",
      "ratio": "16:9",
      "focal": {
          "x": 0.6,
          "y": 0.45
      },
      "loop": "pingpong",
      "duration": 10.711,
      "approved": false,
      "hero": true,
      "files": {
          "mp4_720": "/clips/sailboat-sunset.e825e0b7.720.mp4",
          "mp4_1080": "/clips/sailboat-sunset.e825e0b7.1080.mp4",
          "poster": "/clips/sailboat-sunset.e825e0b7.jpg",
          "poster_1920": "/clips/sailboat-sunset.e825e0b7.poster.1920.jpg"
      }
  },
  "needle-above-clouds": {
      "id": "needle-above-clouds",
      "hash": "c51c7369",
      "entryHash": "0ba7c53c",
      "ratio": "16:9",
      "focal": {
          "x": 0.5,
          "y": 0.45
      },
      "loop": "xfade",
      "duration": 10.511,
      "approved": false,
      "hero": true,
      "files": {
          "mp4_720": "/clips/needle-above-clouds.c51c7369.720.mp4",
          "poster": "/clips/needle-above-clouds.c51c7369.jpg",
          "mp4_1080": "/clips/needle-above-clouds.c51c7369.1080.mp4",
          "poster_1920": "/clips/needle-above-clouds.c51c7369.poster.1920.jpg"
      }
  },
  "yacht-dusk-wake": {
      "id": "yacht-dusk-wake",
      "hash": "15879954",
      "entryHash": "197d84cf",
      "ratio": "16:9",
      "focal": {
          "x": 0.5,
          "y": 0.5
      },
      "loop": "xfade",
      "duration": 8.308,
      "approved": false,
      "hero": true,
      "files": {
          "mp4_720": "/clips/yacht-dusk-wake.15879954.720.mp4",
          "poster": "/clips/yacht-dusk-wake.15879954.jpg",
          "mp4_1080": "/clips/yacht-dusk-wake.15879954.1080.mp4",
          "poster_1920": "/clips/yacht-dusk-wake.15879954.poster.1920.jpg"
      }
  },
  "point-sunset": {
      "id": "point-sunset",
      "hash": "996b8373",
      "entryHash": "f2519675",
      "ratio": "16:9",
      "focal": {
          "x": 0.5,
          "y": 0.5
      },
      "loop": "xfade",
      "duration": 8.508,
      "approved": false,
      "hero": false,
      "files": {
          "mp4_720": "/clips/point-sunset.996b8373.720.mp4",
          "poster": "/clips/point-sunset.996b8373.jpg",
          "mp4_1080": "/clips/point-sunset.996b8373.1080.mp4",
          "poster_1920": "/clips/point-sunset.996b8373.poster.1920.jpg"
      }
  },
  "marina-skyline": {
      "id": "marina-skyline",
      "hash": "194f80fc",
      "entryHash": "0ff00cb2",
      "ratio": "16:9",
      "focal": {
          "x": 0.6,
          "y": 0.5
      },
      "loop": "xfade",
      "duration": 10.511,
      "approved": false,
      "hero": false,
      "files": {
          "mp4_720": "/clips/marina-skyline.194f80fc.720.mp4",
          "poster": "/clips/marina-skyline.194f80fc.jpg",
          "mp4_1080": "/clips/marina-skyline.194f80fc.1080.mp4",
          "poster_1920": "/clips/marina-skyline.194f80fc.poster.1920.jpg"
      }
  },
  "yacht-dusk-side": {
      "id": "yacht-dusk-side",
      "hash": "68e63424",
      "entryHash": "84362a74",
      "ratio": "16:9",
      "focal": {
          "x": 0.5,
          "y": 0.6
      },
      "loop": "xfade",
      "duration": 7.508,
      "approved": false,
      "hero": false,
      "files": {
          "mp4_720": "/clips/yacht-dusk-side.68e63424.720.mp4",
          "poster": "/clips/yacht-dusk-side.68e63424.jpg",
          "mp4_1080": "/clips/yacht-dusk-side.68e63424.1080.mp4",
          "poster_1920": "/clips/yacht-dusk-side.68e63424.poster.1920.jpg"
      }
  },
  "city-rise": {
      "id": "city-rise",
      "hash": "e270f1fa",
      "entryHash": "654cedde",
      "ratio": "16:9",
      "focal": {
          "x": 0.5,
          "y": 0.35
      },
      "loop": "pingpong",
      "duration": 8.709,
      "approved": false,
      "hero": false,
      "files": {
          "mp4_720": "/clips/city-rise.e270f1fa.720.mp4",
          "mp4_1080": "/clips/city-rise.e270f1fa.1080.mp4",
          "poster": "/clips/city-rise.e270f1fa.jpg",
          "poster_1920": "/clips/city-rise.e270f1fa.poster.1920.jpg"
      }
  },
  "spit-golden-hour": {
      "id": "spit-golden-hour",
      "hash": "1bf39bfd",
      "entryHash": "26c30d3a",
      "ratio": "16:9",
      "focal": {
          "x": 0.4,
          "y": 0.5
      },
      "loop": "xfade",
      "duration": 9.509,
      "approved": false,
      "hero": false,
      "files": {
          "mp4_720": "/clips/spit-golden-hour.1bf39bfd.720.mp4",
          "poster": "/clips/spit-golden-hour.1bf39bfd.jpg",
          "mp4_1080": "/clips/spit-golden-hour.1bf39bfd.1080.mp4",
          "poster_1920": "/clips/spit-golden-hour.1bf39bfd.poster.1920.jpg"
      }
  },
  "tug-daylight": {
      "id": "tug-daylight",
      "hash": "c02fefd5",
      "entryHash": "c8a55454",
      "ratio": "16:9",
      "focal": {
          "x": 0.5,
          "y": 0.4
      },
      "loop": "xfade",
      "duration": 7.508,
      "approved": false,
      "hero": false,
      "files": {
          "mp4_720": "/clips/tug-daylight.c02fefd5.720.mp4",
          "poster": "/clips/tug-daylight.c02fefd5.jpg",
          "mp4_1080": "/clips/tug-daylight.c02fefd5.1080.mp4",
          "poster_1920": "/clips/tug-daylight.c02fefd5.poster.1920.jpg"
      }
  },
} as const satisfies Record<string, ClipEntry>;

export type ClipId = keyof typeof clips;
export const clipIds = Object.keys(clips) as ClipId[];
